# Generated by Django 4.1.13 on 2025-03-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('search_query', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Название професси',
                'verbose_name_plural': 'Нахвание профессий',
            },
        ),
        migrations.CreateModel(
            name='VacancyKeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('json_data', models.JSONField()),
                ('key_skills', models.ManyToManyField(to='vacancies.vacancykeywords')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.profession')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
